modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "extrasounds"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.extrasounds]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.extrasounds]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mixins]]
config = "extrasounds.mixins.json"